name: Build

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build
      run: |
        pyinstaller --noconfirm --onefile --console mouse.py
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
          path: ./dist*
